import type { OptionDefinition, SectionId } from './types';

export const LINE_LENGTH_MIN = 40;
export const LINE_LENGTH_MAX = 300;
export const LINE_LENGTH_DEFAULT = 120;

export const SECTIONS: { id: SectionId; title: string; summary: string }[] = [
  { id: 'general', title: 'General Formatting', summary: 'Line endings and how embedded code is treated.' },
  { id: 'wrapping', title: 'Line Length and Wrapping', summary: 'How wide your code may get before it is wrapped.' },
  { id: 'indentation', title: 'Indentation', summary: 'Tabs or spaces, and how far each level is indented.' },
  { id: 'spacing', title: 'Spaces and Blank Lines', summary: 'Spaces inside brackets and around operators, and blank lines.' },
  { id: 'braces', title: 'Braces and Brackets', summary: 'Where opening braces go and how short blocks are laid out.' },
  { id: 'quotes', title: 'Quotes and Semicolons', summary: 'Quote characters, semicolons and trailing commas.' },
  { id: 'imports', title: 'Imports and Comments', summary: 'Import ordering and comment re-flowing.' },
  { id: 'language', title: 'Language-Specific Options', summary: 'Options that only exist for one language or formatter.' },
];

/**
 * Every preference CodeNeat knows about. An option appears here only when at least one integrated
 * formatter really implements it; the per-formatter mapping lives in each adapter's descriptor.
 */
export const CATALOG: OptionDefinition[] = [
  // ───────────────────────────── General
  {
    id: 'lineEndings',
    section: 'general',
    type: 'enum',
    control: 'radio',
    label: 'Line Endings',
    description: 'The invisible character(s) that end each line. "Keep existing" leaves each file as it is.',
    choices: [
      { value: 'auto', label: 'Keep existing' },
      { value: 'lf', label: 'LF (macOS, Linux)', description: 'Unix style \\n' },
      { value: 'crlf', label: 'CRLF (Windows)', description: 'Windows style \\r\\n' },
    ],
    fallback: 'auto',
    codeneatDefault: 'auto',
    keywords: ['endOfLine', 'eol', 'newline', 'crlf', 'lf'],
  },
  {
    id: 'embeddedFormatting',
    section: 'general',
    type: 'enum',
    control: 'radio',
    label: 'Format Embedded Code',
    description: 'Also format code inside other code, such as CSS inside HTML or code blocks in Markdown.',
    choices: [
      { value: 'auto', label: 'Yes, when recognised' },
      { value: 'off', label: 'No, leave it alone' },
    ],
    fallback: 'auto',
    keywords: ['embeddedLanguageFormatting'],
  },

  // ───────────────────────────── Line length and wrapping
  {
    id: 'lineLength',
    section: 'wrapping',
    type: 'number',
    control: 'slider',
    label: 'Preferred Line Length',
    description:
      'How many characters wide a line may be before the formatter tries to wrap it. Most formatters treat this as a goal, not a hard limit: text that cannot be split safely (long strings, URLs) may still be longer.',
    example: 'someFunction(argumentOne, argumentTwo)  →  wraps once it passes this width',
    min: LINE_LENGTH_MIN,
    max: LINE_LENGTH_MAX,
    step: 1,
    unit: 'characters',
    presets: [60, 80, 100, 120, 140, 160],
    fallback: 80,
    codeneatDefault: LINE_LENGTH_DEFAULT,
    keywords: ['printWidth', 'max_width', 'line-length', 'ColumnLimit', 'column', 'width', 'maxColumn'],
  },
  {
    id: 'proseWrap',
    section: 'wrapping',
    type: 'enum',
    control: 'radio',
    label: 'Wrap Text Paragraphs',
    description: 'How paragraphs of plain text (Markdown, long YAML strings) are wrapped.',
    choices: [
      { value: 'preserve', label: 'Leave as written' },
      { value: 'always', label: 'Wrap at the line length' },
      { value: 'never', label: 'One line per paragraph' },
    ],
    fallback: 'preserve',
    keywords: ['proseWrap', 'markdown'],
  },
  {
    id: 'objectWrap',
    section: 'wrapping',
    type: 'enum',
    control: 'radio',
    label: 'Multi-line Objects',
    description: 'What happens to an object that you wrote over several lines but that would fit on one.',
    example: '{\n  a: 1 }   →  keep: stays multi-line · collapse: { a: 1 }',
    choices: [
      { value: 'preserve', label: 'Keep it multi-line' },
      { value: 'collapse', label: 'Collapse when it fits' },
    ],
    fallback: 'preserve',
    keywords: ['objectWrap'],
  },
  {
    id: 'singleAttributePerLine',
    section: 'wrapping',
    type: 'boolean',
    label: 'One Attribute per Line',
    description: 'Put every HTML, Vue or JSX attribute on its own line when an element has more than one.',
    fallback: false,
    keywords: ['singleAttributePerLine', 'html', 'jsx'],
  },
  {
    id: 'operatorLinePosition',
    section: 'wrapping',
    type: 'enum',
    control: 'radio',
    label: 'Operators When Wrapping',
    description: 'When a long expression is split, put the operator at the end of the first line or the start of the next.',
    example: 'end:  a +\\n  b      start:  a\\n  + b',
    choices: [
      { value: 'end', label: 'End of line' },
      { value: 'start', label: 'Start of next line' },
    ],
    fallback: 'end',
    keywords: ['experimentalOperatorPosition', 'BreakBeforeBinaryOperators', 'binary-next-line'],
  },

  // ───────────────────────────── Indentation
  {
    id: 'indentStyle',
    section: 'indentation',
    type: 'enum',
    control: 'radio',
    label: 'Indent Using',
    description: 'Indent with space characters or with tab characters.',
    choices: [
      { value: 'spaces', label: 'Spaces' },
      { value: 'tabs', label: 'Tabs' },
    ],
    fallback: 'spaces',
    keywords: ['useTabs', 'hard_tabs', 'indent-type', 'UseTab', 'insertSpaces'],
  },
  {
    id: 'indentSize',
    section: 'indentation',
    type: 'number',
    control: 'input',
    label: 'Indentation Size',
    description: 'How many spaces one indentation level is (or how wide a tab is considered to be).',
    min: 1,
    max: 16,
    step: 1,
    unit: 'spaces',
    presets: [2, 4, 8],
    fallback: 4,
    keywords: ['tabWidth', 'tab_spaces', 'indent-width', 'IndentWidth', 'tabSize'],
  },
  {
    id: 'continuationIndent',
    section: 'indentation',
    type: 'number',
    control: 'input',
    label: 'Continuation Indentation',
    description: 'Extra indentation for the second and later lines of a statement that was wrapped.',
    min: 0,
    max: 16,
    step: 1,
    unit: 'spaces',
    presets: [2, 4, 8],
    fallback: 4,
    keywords: ['ContinuationIndentWidth', 'continuation'],
  },
  {
    id: 'indentCaseLabels',
    section: 'indentation',
    type: 'boolean',
    label: 'Indent Case Labels in Switch',
    description: 'Indent "case" labels one level deeper than their "switch" statement.',
    example: 'switch (x) {\n  case 1:   ← indented when on',
    fallback: false,
    keywords: ['IndentCaseLabels', 'switch', 'case', 'case-indent'],
  },
  {
    id: 'parenthesesIndent',
    section: 'indentation',
    type: 'enum',
    control: 'radio',
    label: 'Wrapped Arguments in Parentheses',
    description: 'How arguments are placed when a call or declaration does not fit on one line.',
    choices: [
      { value: 'align', label: 'Align under the first argument' },
      { value: 'indent', label: 'Indent by the continuation indentation' },
      { value: 'block', label: 'Each on its own line, closing bracket on a new line' },
    ],
    fallback: 'align',
    keywords: ['AlignAfterOpenBracket', 'parentheses'],
  },
  {
    id: 'indentScriptAndStyle',
    section: 'indentation',
    type: 'boolean',
    label: 'Indent <script> and <style> in Vue Files',
    description: 'Indent the code inside the <script> and <style> blocks of a Vue single-file component.',
    fallback: false,
    keywords: ['vueIndentScriptAndStyle', 'vue'],
  },
  {
    id: 'htmlWhitespace',
    section: 'indentation',
    type: 'enum',
    control: 'select',
    label: 'HTML Nesting and Whitespace',
    description:
      'Whether spaces between HTML tags are meaningful. "Ignore" gives the cleanest nested indentation but may add or remove visible spaces between inline elements.',
    choices: [
      { value: 'css', label: 'Follow CSS display rules (safe)' },
      { value: 'strict', label: 'Treat all whitespace as meaningful' },
      { value: 'ignore', label: 'Ignore whitespace (cleanest nesting)' },
    ],
    fallback: 'css',
    keywords: ['htmlWhitespaceSensitivity', 'html', 'nested'],
  },

  // ───────────────────────────── Spaces and blank lines
  {
    id: 'bracketSpacing',
    section: 'spacing',
    type: 'boolean',
    label: 'Spaces Inside Object Braces',
    description: 'Put a space after "{" and before "}" in objects and similar literals.',
    example: 'on: { a: 1 }    off: {a: 1}',
    fallback: true,
    keywords: ['bracketSpacing', 'object'],
  },
  {
    id: 'spaceBeforeParens',
    section: 'spacing',
    type: 'enum',
    control: 'radio',
    label: 'Space Before Opening Parenthesis',
    description: 'When a space is placed before "(".',
    example: 'control: if (x) f(x)   always: if (x) f (x)   never: if(x) f(x)',
    choices: [
      { value: 'control', label: 'After if, for, while only' },
      { value: 'always', label: 'Always' },
      { value: 'never', label: 'Never' },
    ],
    fallback: 'control',
    keywords: ['SpaceBeforeParens'],
  },
  {
    id: 'spacesInParens',
    section: 'spacing',
    type: 'boolean',
    label: 'Spaces Inside Parentheses',
    description: 'Put a space after "(" and before ")".',
    example: 'on: f( a, b )    off: f(a, b)',
    fallback: false,
    keywords: ['SpacesInParentheses', 'SpacesInParens'],
  },
  {
    id: 'spaceAroundAssignment',
    section: 'spacing',
    type: 'boolean',
    label: 'Space Before Assignment Operators',
    description: 'Put a space before "=", "+=" and other assignment operators.',
    example: 'on: a = 5    off: a= 5',
    fallback: true,
    keywords: ['SpaceBeforeAssignmentOperators', 'assignment'],
  },
  {
    id: 'maxBlankLines',
    section: 'spacing',
    type: 'number',
    control: 'input',
    label: 'Maximum Blank Lines in a Row',
    description: 'Longer runs of empty lines are shortened to this many.',
    min: 0,
    max: 10,
    step: 1,
    unit: 'lines',
    fallback: 1,
    keywords: ['MaxEmptyLinesToKeep', 'maximumBlankLines', 'allowedBlankLines', 'blank lines'],
  },
  {
    id: 'separateDefinitions',
    section: 'spacing',
    type: 'enum',
    control: 'radio',
    label: 'Blank Line Between Functions and Classes',
    description: 'Whether a blank line is added or removed between functions, methods and classes.',
    choices: [
      { value: 'leave', label: 'Leave as written' },
      { value: 'always', label: 'Always add one' },
      { value: 'never', label: 'Remove them' },
    ],
    fallback: 'leave',
    keywords: ['SeparateDefinitionBlocks', 'methods'],
  },

  // ───────────────────────────── Braces and brackets
  {
    id: 'braceStyle',
    section: 'braces',
    type: 'enum',
    control: 'select',
    label: 'Opening Brace Position',
    description: 'Where the opening "{" of functions, classes and control statements is placed.',
    example: 'same line:  if (x) {        next line:  if (x)\\n            {',
    choices: [
      { value: 'attach', label: 'Same line' },
      { value: 'allman', label: 'Next line (Allman)' },
      { value: 'stroustrup', label: 'Same line, "else" on its own line (Stroustrup)' },
      { value: 'linux', label: 'Next line for functions only (Linux kernel)' },
      { value: 'mozilla', label: 'Mozilla' },
      { value: 'webkit', label: 'WebKit' },
      { value: 'gnu', label: 'Next line, indented (GNU)' },
      { value: 'whitesmiths', label: 'Next line with body indented (Whitesmiths)' },
    ],
    fallback: 'attach',
    keywords: ['BreakBeforeBraces', 'brace', 'allman', 'K&R', 'OTBS'],
  },
  {
    id: 'bracketSameLine',
    section: 'braces',
    type: 'boolean',
    label: 'Closing ">" on the Last Attribute Line',
    description: 'Keep the ">" of a multi-line HTML or JSX tag on the last attribute line instead of on its own line.',
    fallback: false,
    keywords: ['bracketSameLine', 'jsx', 'html'],
  },
  {
    id: 'arrowParens',
    section: 'braces',
    type: 'enum',
    control: 'radio',
    label: 'Parentheses Around a Single Arrow Parameter',
    description: 'Whether a lone arrow-function parameter is wrapped in parentheses.',
    example: 'always: (x) => x    avoid: x => x',
    choices: [
      { value: 'always', label: 'Always' },
      { value: 'avoid', label: 'Only when needed' },
    ],
    fallback: 'always',
    keywords: ['arrowParens', 'lambda'],
  },
  {
    id: 'shortFunctionsOnOneLine',
    section: 'braces',
    type: 'enum',
    control: 'select',
    label: 'Short Functions on One Line',
    description: 'Which short functions may stay on a single line.',
    example: 'int f() { return 0; }',
    choices: [
      { value: 'none', label: 'Never' },
      { value: 'empty', label: 'Only empty functions' },
      { value: 'inline', label: 'Functions defined inside a class' },
      { value: 'all', label: 'Any function that fits' },
    ],
    fallback: 'all',
    keywords: ['AllowShortFunctionsOnASingleLine'],
  },
  {
    id: 'shortIfOnOneLine',
    section: 'braces',
    type: 'boolean',
    label: 'Short "if" on One Line',
    description: 'Allow a short "if" statement without "else" to stay on one line.',
    example: 'if (x) return;',
    fallback: false,
    keywords: ['AllowShortIfStatementsOnASingleLine'],
  },

  // ───────────────────────────── Quotes, semicolons, commas
  {
    id: 'quoteStyle',
    section: 'quotes',
    type: 'enum',
    control: 'radio',
    label: 'Quotes',
    description:
      'Which quote character strings use. The formatter picks the other one when that avoids escaping.',
    example: "single: 'text'    double: \"text\"",
    choices: [
      { value: 'double', label: 'Double "…"' },
      { value: 'single', label: "Single '…'" },
      { value: 'preserve', label: 'Keep as written' },
    ],
    fallback: 'double',
    keywords: ['singleQuote', 'quote-style', 'quotes'],
  },
  {
    id: 'jsxQuoteStyle',
    section: 'quotes',
    type: 'enum',
    control: 'radio',
    label: 'Quotes in JSX Attributes',
    description: 'Quote character for attribute values inside JSX.',
    choices: [
      { value: 'double', label: 'Double "…"' },
      { value: 'single', label: "Single '…'" },
    ],
    fallback: 'double',
    keywords: ['jsxSingleQuote'],
  },
  {
    id: 'quoteProps',
    section: 'quotes',
    type: 'enum',
    control: 'radio',
    label: 'Quotes Around Object Keys',
    description: 'When the keys of an object are quoted.',
    choices: [
      { value: 'as-needed', label: 'Only when required' },
      { value: 'consistent', label: 'All, if any key needs them' },
      { value: 'preserve', label: 'Keep as written' },
    ],
    fallback: 'as-needed',
    keywords: ['quoteProps'],
  },
  {
    id: 'semicolons',
    section: 'quotes',
    type: 'enum',
    control: 'radio',
    label: 'Semicolons',
    description: 'Whether statements end with a semicolon. Use Reset to return to the formatter default.',
    choices: [
      { value: 'always', label: 'Add semicolons' },
      { value: 'never', label: 'Leave them out', description: 'Only added where the language requires one.' },
    ],
    fallback: 'always',
    keywords: ['semi', 'semicolon'],
  },
  {
    id: 'trailingCommas',
    section: 'quotes',
    type: 'enum',
    control: 'radio',
    label: 'Trailing Commas',
    description: 'Whether the last item of a multi-line list, object or parameter list is followed by a comma.',
    choices: [
      { value: 'all', label: 'Wherever possible' },
      { value: 'es5', label: 'In lists and objects only' },
      { value: 'none', label: 'Never' },
    ],
    fallback: 'all',
    keywords: ['trailingComma'],
  },

  // ───────────────────────────── Imports and comments
  {
    id: 'sortImports',
    section: 'imports',
    type: 'boolean',
    label: 'Sort Imports',
    description:
      'Put import / include lines into a consistent order. This reorders lines but never adds or removes an import.',
    fallback: false,
    keywords: ['SortIncludes', 'reorder_imports', 'isort', 'organize imports', 'ordered_imports'],
  },
  {
    id: 'removeUnusedImports',
    section: 'imports',
    type: 'boolean',
    semantic: true,
    label: 'Remove Unused Imports',
    description:
      'Delete imports that nothing in the file uses. This changes code rather than layout, so it is off unless you switch it on.',
    fallback: false,
    keywords: ['unused imports', 'skip-removing-unused-imports', 'no_unused_imports'],
  },
  {
    id: 'reflowComments',
    section: 'imports',
    type: 'boolean',
    label: 'Re-wrap Long Comments',
    description: 'Break comments that are longer than the line length onto several lines.',
    fallback: true,
    keywords: ['ReflowComments', 'comments'],
  },
  {
    id: 'formatDocComments',
    section: 'imports',
    type: 'boolean',
    label: 'Format Documentation Comments',
    description: 'Tidy documentation comments such as Javadoc, or code examples inside Python docstrings.',
    fallback: true,
    keywords: ['javadoc', 'docstring', 'docstring-code-format', 'skip-javadoc-formatting'],
  },

  // ───────────────────────────── Language specific
  {
    id: 'experimentalTernaries',
    section: 'language',
    type: 'boolean',
    label: 'JavaScript: New Ternary Layout',
    description: 'Use Prettier\'s newer layout for "condition ? a : b" chains, with the question mark at the end of the line.',
    fallback: false,
    keywords: ['experimentalTernaries', 'ternary'],
  },
  {
    id: 'pythonMagicTrailingComma',
    section: 'language',
    type: 'boolean',
    label: 'Python: Trailing Comma Keeps Lists Expanded',
    description:
      'When a list or call already ends with a trailing comma, keep it one-item-per-line even if it would fit on a single line.',
    fallback: true,
    keywords: ['skip-magic-trailing-comma', 'magic trailing comma'],
  },
  {
    id: 'javaStyleGuide',
    section: 'language',
    type: 'enum',
    control: 'radio',
    label: 'Java: Style Guide',
    description: 'google-java-format implements two fixed styles.',
    choices: [
      { value: 'google', label: 'Google Style (2 spaces)' },
      { value: 'aosp', label: 'Android / AOSP (4 spaces)' },
    ],
    fallback: 'google',
    keywords: ['aosp', 'google-java-format'],
  },
  {
    id: 'kotlinStyleGuide',
    section: 'language',
    type: 'enum',
    control: 'radio',
    label: 'Kotlin: Style Guide',
    description: 'The fixed style ktfmt or ktlint follows.',
    choices: [
      { value: 'meta', label: 'Meta (ktfmt default)' },
      { value: 'google', label: 'Google' },
      { value: 'kotlinlang', label: 'Kotlin official' },
      { value: 'android', label: 'Android Studio (ktlint)' },
    ],
    fallback: 'kotlinlang',
    keywords: ['ktfmt', 'ktlint', 'ktlint_code_style'],
  },
  {
    id: 'cppBaseStyle',
    section: 'language',
    type: 'enum',
    control: 'select',
    label: 'C / C++: Base Style',
    description: 'The ready-made clang-format style that your other preferences are layered on top of.',
    choices: [
      { value: 'LLVM', label: 'LLVM' },
      { value: 'Google', label: 'Google' },
      { value: 'Chromium', label: 'Chromium' },
      { value: 'Mozilla', label: 'Mozilla' },
      { value: 'WebKit', label: 'WebKit' },
      { value: 'Microsoft', label: 'Microsoft' },
      { value: 'GNU', label: 'GNU' },
    ],
    fallback: 'LLVM',
    keywords: ['BasedOnStyle', 'clang-format'],
  },
  {
    id: 'rustEdition',
    section: 'language',
    type: 'enum',
    control: 'select',
    label: 'Rust: Edition',
    description: 'The Rust edition rustfmt uses to read your code when no Cargo project config is found.',
    choices: [
      { value: '2015', label: '2015' },
      { value: '2018', label: '2018' },
      { value: '2021', label: '2021' },
      { value: '2024', label: '2024' },
    ],
    fallback: '2021',
    keywords: ['edition', 'rustfmt'],
  },
  {
    id: 'phpRuleSet',
    section: 'language',
    type: 'enum',
    control: 'select',
    label: 'PHP: Rule Set',
    description: 'The coding standard PHP-CS-Fixer applies.',
    choices: [
      { value: '@PSR12', label: 'PSR-12' },
      { value: '@PER-CS', label: 'PER Coding Style' },
      { value: '@Symfony', label: 'Symfony' },
      { value: '@PhpCsFixer', label: 'PHP-CS-Fixer' },
    ],
    fallback: '@PSR12',
    keywords: ['php-cs-fixer', 'psr'],
  },
  {
    id: 'sqlDialect',
    section: 'language',
    type: 'enum',
    control: 'select',
    label: 'SQL: Dialect',
    description: 'The SQL flavour your files are written in.',
    choices: [
      { value: 'ansi', label: 'Standard SQL' },
      { value: 'postgres', label: 'PostgreSQL' },
      { value: 'mysql', label: 'MySQL' },
      { value: 'mariadb', label: 'MariaDB' },
      { value: 'sqlite', label: 'SQLite' },
      { value: 'tsql', label: 'SQL Server (T-SQL)' },
      { value: 'oracle', label: 'Oracle PL/SQL' },
      { value: 'bigquery', label: 'BigQuery' },
      { value: 'snowflake', label: 'Snowflake' },
      { value: 'redshift', label: 'Redshift' },
      { value: 'sparksql', label: 'Spark SQL' },
      { value: 'trino', label: 'Trino' },
      { value: 'hive', label: 'Hive' },
      { value: 'db2', label: 'Db2' },
    ],
    fallback: 'ansi',
    keywords: ['dialect', 'sqlfluff', 'sql-formatter'],
  },
  {
    id: 'sqlKeywordCase',
    section: 'language',
    type: 'enum',
    control: 'radio',
    label: 'SQL: Keyword Case',
    description: 'How keywords such as SELECT and FROM are written.',
    choices: [
      { value: 'preserve', label: 'Keep as written' },
      { value: 'upper', label: 'UPPER CASE' },
      { value: 'lower', label: 'lower case' },
    ],
    fallback: 'preserve',
    keywords: ['keywordCase'],
  },
  {
    id: 'shellDialect',
    section: 'language',
    type: 'enum',
    control: 'select',
    label: 'Shell: Dialect',
    description: 'Which shell language the script is written in.',
    choices: [
      { value: 'auto', label: 'Detect from the file' },
      { value: 'bash', label: 'Bash' },
      { value: 'posix', label: 'POSIX sh' },
      { value: 'mksh', label: 'mksh' },
      { value: 'bats', label: 'Bats' },
    ],
    fallback: 'auto',
    keywords: ['shfmt', '-ln'],
  },
  {
    id: 'shellSpaceRedirects',
    section: 'language',
    type: 'boolean',
    label: 'Shell: Space After Redirect Operators',
    description: 'Write "> file" instead of ">file".',
    fallback: false,
    keywords: ['space-redirects', '-sr'],
  },
  {
    id: 'shellFunctionNextLine',
    section: 'language',
    type: 'boolean',
    label: 'Shell: Function Brace on Next Line',
    description: 'Put the opening brace of a function on its own line.',
    fallback: false,
    keywords: ['func-next-line', '-fn'],
  },
  {
    id: 'luaCallParentheses',
    section: 'language',
    type: 'enum',
    control: 'select',
    label: 'Lua: Parentheses on Calls',
    description: 'Whether calls with a single string or table argument keep their parentheses.',
    choices: [
      { value: 'Always', label: 'Always use parentheses' },
      { value: 'NoSingleString', label: 'Omit for a single string' },
      { value: 'NoSingleTable', label: 'Omit for a single table' },
      { value: 'None', label: 'Omit for a single string or table' },
    ],
    fallback: 'Always',
    keywords: ['call-parentheses', 'stylua'],
  },
  {
    id: 'xmlWhitespace',
    section: 'language',
    type: 'enum',
    control: 'radio',
    label: 'XML: Whitespace in Text',
    description:
      'Whether whitespace inside elements is meaningful. "Ignore" allows real re-indentation but changes text content whitespace.',
    choices: [
      { value: 'strict', label: 'Meaningful (do not touch)' },
      { value: 'preserve', label: 'Meaningful only inside text' },
      { value: 'ignore', label: 'Not meaningful (re-indent freely)' },
    ],
    fallback: 'strict',
    keywords: ['xmlWhitespaceSensitivity'],
  },
  {
    id: 'xmlSelfClosingSpace',
    section: 'language',
    type: 'boolean',
    label: 'XML: Space Before "/>"',
    description: 'Write <tag /> instead of <tag/>.',
    fallback: true,
    keywords: ['xmlSelfClosingSpace'],
  },
  {
    id: 'xmlSortAttributes',
    section: 'language',
    type: 'boolean',
    label: 'XML: Sort Attributes by Name',
    description: 'Order the attributes of every element alphabetically.',
    fallback: false,
    keywords: ['xmlSortAttributesByKey'],
  },
  {
    id: 'tomlAlignEntries',
    section: 'language',
    type: 'boolean',
    label: 'TOML: Align "=" Signs',
    description: 'Line up the "=" of consecutive entries in a column.',
    fallback: false,
    keywords: ['align_entries', 'alignEntries', 'taplo'],
  },
  {
    id: 'tomlReorderKeys',
    section: 'language',
    type: 'boolean',
    label: 'TOML: Sort Keys Alphabetically',
    description: 'Reorder the keys within each table alphabetically.',
    fallback: false,
    keywords: ['reorder_keys', 'reorderKeys', 'taplo'],
  },
  {
    id: 'dockerfileSpaceRedirects',
    section: 'language',
    type: 'boolean',
    label: 'Dockerfile: Space After Redirect Operators',
    description: 'Write "> file" instead of ">file" inside RUN commands.',
    fallback: false,
    keywords: ['dockerfmt', 'space-redirects'],
  },
];

const BY_ID = new Map(CATALOG.map((option) => [option.id, option]));

export function getOption(id: string): OptionDefinition | undefined {
  return BY_ID.get(id);
}

export function isKnownOption(id: string): boolean {
  return BY_ID.has(id);
}
