import * as fs from 'node:fs';
import * as path from 'node:path';
import ignore, { type Ignore } from 'ignore';
import { languageFromFileName } from '../shared/languages';
import type { LanguageDefinition } from '../shared/types';
import { type CancellationSignal, NEVER_CANCELLED } from './process';

/** Always skipped during workspace formatting (gitignore syntax). */
export const DEFAULT_EXCLUDES = [
  '.git/',
  '.hg/',
  '.svn/',
  'node_modules/',
  'bower_components/',
  'vendor/',
  'dist/',
  'build/',
  'out/',
  'target/',
  'obj/',
  'coverage/',
  '.next/',
  '.nuxt/',
  '.svelte-kit/',
  '.output/',
  '.cache/',
  '.turbo/',
  '.gradle/',
  '.dart_tool/',
  '.terraform/',
  '.venv/',
  'venv/',
  '__pycache__/',
  '.mypy_cache/',
  '.pytest_cache/',
  '.tox/',
  '.idea/',
  '.vscode-test/',
  'Pods/',
  'DerivedData/',
  '*.min.js',
  '*.min.css',
  '*.bundle.js',
  '*.map',
  '*.snap',
  '*.lock',
  '*.generated.*',
  '*.g.dart',
  '*.freezed.dart',
  '*.pb.go',
  '*.pb.cc',
  '*.pb.h',
  '*_pb2.py',
  '*_pb2_grpc.py',
  '*.designer.cs',
  '*.Designer.cs',
  'package-lock.json',
  'npm-shrinkwrap.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'composer.lock',
  'Cargo.lock',
  'Gemfile.lock',
  'poetry.lock',
  'Pipfile.lock',
  'go.sum',
  '.terraform.lock.hcl',
];

const GENERATED_MARKERS = [/@generated/, /\bDO NOT EDIT\b/, /\bauto-?generated\b/i, /\bAutomatically generated\b/i, /<auto-generated/i];

/** True when the beginning of a file says that the file is generated by a tool. */
export function looksGenerated(text: string): boolean {
  const head = text.slice(0, 2000);
  return GENERATED_MARKERS.some((marker) => marker.test(head));
}

/** True when the data looks like binary content (contains NUL bytes). */
export function looksBinary(data: Uint8Array): boolean {
  const limit = Math.min(data.length, 8000);
  for (let index = 0; index < limit; index++) {
    if (data[index] === 0) {
      return true;
    }
  }
  return false;
}

export interface ScanOptions {
  languages: LanguageDefinition[];
  /** Extra exclusion patterns in gitignore syntax. */
  exclude: string[];
  useGitignore: boolean;
  maxFiles?: number;
  token?: CancellationSignal;
  onDirectory?(directory: string): void;
}

export interface ScannedFile {
  path: string;
  /** Path relative to the scanned root, with forward slashes. */
  relative: string;
  languageId: string;
}

export interface ScanResult {
  files: ScannedFile[];
  /** True when the scan stopped early because `maxFiles` was reached. */
  truncated: boolean;
  skippedByIgnore: number;
}

interface Scope {
  base: string;
  matcher: Ignore;
}

function safeAdd(matcher: Ignore, patterns: string[]): void {
  for (const pattern of patterns) {
    try {
      matcher.add(pattern);
    } catch {
      // an invalid pattern must not abort the scan
    }
  }
}

function isIgnored(scopes: Scope[], absolute: string, isDirectory: boolean): boolean {
  let ignored = false;
  for (const scope of scopes) {
    const relative = path.relative(scope.base, absolute).split(path.sep).join('/');
    if (!relative || relative.startsWith('..')) {
      continue;
    }
    const result = scope.matcher.test(isDirectory ? `${relative}/` : relative);
    if (result.ignored) {
      ignored = true;
    } else if (result.unignored) {
      ignored = false;
    }
  }
  return ignored;
}

async function readGitignore(directory: string): Promise<string[] | undefined> {
  try {
    const content = await fs.promises.readFile(path.join(directory, '.gitignore'), 'utf8');
    return content.split(/\r?\n/);
  } catch {
    return undefined;
  }
}

/** Collects .gitignore files that sit above the scanned folder, up to the repository root. */
async function parentScopes(root: string): Promise<Scope[]> {
  const scopes: Scope[] = [];
  let current = path.dirname(root);
  for (let depth = 0; depth < 30; depth++) {
    const lines = await readGitignore(current);
    if (lines) {
      const matcher = ignore();
      safeAdd(matcher, lines);
      scopes.unshift({ base: current, matcher });
    }
    const isRepositoryRoot = await fs.promises.stat(path.join(current, '.git')).then(
      () => true,
      () => false,
    );
    const parent = path.dirname(current);
    if (isRepositoryRoot || parent === current) {
      break;
    }
    current = parent;
  }
  return scopes;
}

/** Finds the files under `root` that CodeNeat can format, honouring all exclusions. */
export async function scanFolder(root: string, options: ScanOptions): Promise<ScanResult> {
  const token = options.token ?? NEVER_CANCELLED;
  const maxFiles = options.maxFiles ?? 20000;
  const files: ScannedFile[] = [];
  let truncated = false;
  let skippedByIgnore = 0;

  const builtin = ignore();
  safeAdd(builtin, [...DEFAULT_EXCLUDES, ...options.exclude]);
  const rootScopes: Scope[] = [{ base: root, matcher: builtin }];
  if (options.useGitignore) {
    const repositoryMarker = await fs.promises.stat(path.join(root, '.git')).then(
      () => true,
      () => false,
    );
    if (!repositoryMarker) {
      rootScopes.push(...(await parentScopes(root)));
    }
  }

  const walk = async (directory: string, inherited: Scope[]): Promise<void> => {
    if (token.isCancellationRequested || truncated) {
      return;
    }
    options.onDirectory?.(directory);
    let scopes = inherited;
    if (options.useGitignore) {
      const lines = await readGitignore(directory);
      if (lines) {
        const matcher = ignore();
        safeAdd(matcher, lines);
        scopes = [...inherited, { base: directory, matcher }];
      }
    }
    let entries: fs.Dirent[];
    try {
      entries = await fs.promises.readdir(directory, { withFileTypes: true });
    } catch {
      return;
    }
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      if (token.isCancellationRequested || truncated) {
        return;
      }
      const absolute = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) {
        continue;
      }
      if (entry.isDirectory()) {
        if (isIgnored(scopes, absolute, true)) {
          skippedByIgnore++;
          continue;
        }
        await walk(absolute, scopes);
      } else if (entry.isFile()) {
        const language = languageFromFileName(entry.name, options.languages);
        if (!language) {
          continue;
        }
        if (isIgnored(scopes, absolute, false)) {
          skippedByIgnore++;
          continue;
        }
        if (files.length >= maxFiles) {
          truncated = true;
          return;
        }
        files.push({ path: absolute, relative: path.relative(root, absolute).split(path.sep).join('/'), languageId: language.id });
      }
    }
  };

  await walk(root, rootScopes);
  return { files, truncated, skippedByIgnore };
}
