// Bundled and executed by scripts/gen-docs.mjs. Writes the reference tables from the real descriptors
// so the documentation can never drift from what the code declares.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createBuiltinAdapters } from '../src/core/registry';
import { CATALOG, SECTIONS } from '../src/shared/catalog';
import { LANGUAGES } from '../src/shared/languages';
import { BUILTIN_PROFILES } from '../src/shared/profiles';
import { PRECEDENCE } from '../src/shared/resolve';

const root = process.argv[2];
const descriptors = createBuiltinAdapters().map((adapter) => adapter.descriptor);
const byId = new Map(descriptors.map((descriptor) => [descriptor.id, descriptor]));

const cell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const row = (cells: string[]): string => `| ${cells.map(cell).join(' | ')} |`;
const GENERATED = '<!-- Generated by `npm run docs` from the formatter descriptors. Do not edit by hand. -->';

// ── languages.md
{
  const lines = ['# Supported languages', '', GENERATED, ''];
  lines.push(
    'CodeNeat formats every language with a real, language-aware formatting engine.',
    '',
    '- **Built in** engines work immediately; there is nothing to install.',
    '- **Install once** engines are the official formatter of that language. CodeNeat detects it, and offers to install it for you when it is missing.',
    '',
    'When a language lists more than one formatter, CodeNeat uses the first one that is available, and you can choose another in the dashboard.',
    '',
  );
  for (const group of ['Web', 'Backend', 'Scripting and data'] as const) {
    lines.push(`## ${group}`, '', row(['Language', 'Formatter', 'Availability', 'Line length', 'Format selection']), row(['---', '---', '---', '---', '---']));
    for (const language of LANGUAGES.filter((candidate) => candidate.group === group)) {
      language.formatters.forEach((formatterId, index) => {
        const descriptor = byId.get(formatterId);
        if (!descriptor) {
          return;
        }
        lines.push(
          row([
            index === 0 ? `**${language.label}**` : '',
            `${descriptor.displayName}${index === 0 ? '' : ' (alternative)'}`,
            descriptor.kind === 'bundled' ? 'Built in' : 'Install once',
            descriptor.lineLength === 'preferred' ? 'Preferred width' : 'Not configurable',
            descriptor.rangeLanguages.includes(language.id) ? 'Yes' : 'No',
          ]),
        );
      });
    }
    lines.push('');
  }
  lines.push('File extensions', '---------------', '', row(['Language', 'VS Code language ids', 'Extensions and file names']), row(['---', '---', '---']));
  for (const language of LANGUAGES) {
    lines.push(row([language.label, language.vscodeIds.join(', '), [...language.extensions, ...(language.filenames ?? [])].join(', ')]));
  }
  lines.push('', 'Languages that are not listed can be added with a [custom formatter](configuration.md#custom-formatters).', '');
  writeFileSync(join(root, 'docs', 'languages.md'), lines.join('\n'));
}

// ── formatters.md
{
  const lines = ['# Formatter installation guide', '', GENERATED, ''];
  lines.push(
    'CodeNeat never downloads or installs anything. Install the formatter yourself with one of the commands below, then run **CodeNeat: Re-detect Installed Formatters** (or press *Re-detect* on the Formatter Management page).',
    '',
    'CodeNeat looks for a formatter in this order: the path you set on the Formatter Management page (`codeneat.toolPaths`), a project-local installation (trusted workspaces only), then your `PATH`.',
    '',
  );
  for (const descriptor of descriptors) {
    const languages = LANGUAGES.filter((language) => descriptor.languages.includes(language.id)).map((language) => language.label);
    lines.push(`## ${descriptor.displayName}`, '');
    lines.push(`- **Languages:** ${languages.join(', ')}`);
    lines.push(`- **Engine and licence:** ${descriptor.engine} — ${descriptor.license}`);
    lines.push(`- **Needs:** ${descriptor.requirement}`);
    if (descriptor.kind === 'external') {
      lines.push(`- **Looks for:** \`${descriptor.executables.join('`, `')}\``);
      lines.push(`- **Install:** ${descriptor.install.summary}`);
      for (const command of descriptor.install.commands) {
        lines.push(`  - ${command.label}: \`${command.command}\``);
      }
      lines.push(`- **Guide:** ${descriptor.install.url}`);
    }
    if (descriptor.configFiles.length > 0) {
      lines.push(`- **Project configuration it reads:** ${descriptor.configFiles.map((file) => `\`${file}\``).join(', ')}`);
    }
    const options = CATALOG.filter((option) => descriptor.options[option.id]);
    lines.push(`- **Options CodeNeat can set:** ${options.length === 0 ? 'none' : options.map((option) => `${option.label} (\`${descriptor.options[option.id].native}\`)`).join('; ')}`);
    const fixed = Object.entries(descriptor.fixed);
    if (fixed.length > 0) {
      lines.push(`- **Fixed by the formatter:** ${fixed.map(([, entry]) => entry.reason).join(' ')}`);
    }
    if (descriptor.limitations.length > 0) {
      lines.push('- **Limitations:**', ...descriptor.limitations.map((limitation) => `  - ${limitation}`));
    }
    lines.push('');
  }
  writeFileSync(join(root, 'docs', 'formatters.md'), lines.join('\n'));
}

// ── options.md
{
  const lines = ['# Formatting options reference', '', GENERATED, ''];
  lines.push(
    'These are the option names used in `codeneat.style`, in `codeneat.languages.<language>.style` and in profiles. Every option can be changed in the dashboard; you only need these names if you edit `settings.json` by hand.',
    '',
    'An option only has an effect for formatters that support it. The dashboard disables the others and explains why.',
    '',
  );
  for (const section of SECTIONS) {
    lines.push(`## ${section.title}`, '', row(['Option (`id`)', 'Values', 'Supported by']), row(['---', '---', '---']));
    for (const option of CATALOG.filter((candidate) => candidate.section === section.id)) {
      const values =
        option.type === 'boolean' ? '`true`, `false`' : option.type === 'number' ? `${option.min}–${option.max}${option.codeneatDefault !== undefined ? ` (CodeNeat default ${option.codeneatDefault})` : ''}` : option.choices.map((choice) => `\`${choice.value}\``).join(', ');
      const supporters = descriptors.filter((descriptor) => descriptor.options[option.id]).map((descriptor) => descriptor.displayName);
      lines.push(row([`**${option.label}** (\`${option.id}\`)${option.semantic ? ' — changes code, off by default' : ''}<br>${option.description}`, values, supporters.length > 8 ? `${supporters.slice(0, 8).join(', ')} and ${supporters.length - 8} more` : supporters.join(', ')]));
    }
    lines.push('');
  }
  lines.push('## Built-in profiles', '', row(['Profile (`id`)', 'Description', 'Values']), row(['---', '---', '---']));
  for (const profile of BUILTIN_PROFILES) {
    lines.push(row([`**${profile.name}** (\`${profile.id}\`)`, profile.description ?? '', `\`${JSON.stringify(profile.style)}\``]));
  }
  lines.push('', '## Precedence', '', 'When an option is set in several places, the later entry wins:', '');
  PRECEDENCE.forEach((entry, index) => lines.push(`${index + 1}. ${entry.label}`));
  lines.push('');
  writeFileSync(join(root, 'docs', 'options.md'), lines.join('\n'));
}
console.log('docs: languages.md, formatters.md, options.md written');
