// Generates src/shared/samples.ts from tests/fixtures so the live preview and the tests share one source.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fixtures = join(root, 'tests', 'fixtures');
const entries = [];
for (const language of readdirSync(fixtures, { withFileTypes: true })) {
  if (!language.isDirectory()) {
    continue;
  }
  const file = readdirSync(join(fixtures, language.name)).find((name) => name.startsWith('input') || name === 'Dockerfile');
  if (file) {
    entries.push([language.name, readFileSync(join(fixtures, language.name, file), 'utf8')]);
  }
}
entries.sort(([a], [b]) => a.localeCompare(b));
const body = entries.map(([id, text]) => `  ${JSON.stringify(id)}: ${JSON.stringify(text)},`).join('\n');
const output = `// Generated by scripts/gen-samples.mjs from tests/fixtures. Do not edit by hand.\n\n/** Deliberately untidy sample code per language, used by the live preview. */\nexport const SAMPLES: Record<string, string> = {\n${body}\n};\n`;
writeFileSync(join(root, 'src', 'shared', 'samples.ts'), output);
console.log(`samples: ${entries.length} languages`);
